name: Python Workflow

on:
  workflow_dispatch: # Manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
      working-directory: .github/workflows

    - name: Run Python script
      run: |
        python hello_world.py
